apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projectinitializes.redhatcop.redhat.io
spec:
  group: redhatcop.redhat.io
  names:
    kind: ProjectInitialize
    listKind: ProjectInitializeList
    plural: projectinitializes
    singular: projectinitialize
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ProjectInitialize is the Schema for the projectinitializes API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ProjectInitializeSpec defines the desired state of ProjectInitialize
          properties:
            cluster:
              type: string
            desc:
              type: string
            displayName:
              type: string
            env:
              type: string
            git:
              description: Git
              properties:
                accountSecret:
                  description: The token or credentials of the account that the template
                    will copy to
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                desc:
                  description: Description of the repository to create/clone
                  type: string
                gittype:
                  description: The host platform type
                  enum:
                  - GitHub
                  - GitLab
                  - BitBucket
                  type: string
                owner:
                  description: Account to copy template
                  type: string
                private:
                  description: Private or public repository
                  type: boolean
                ref:
                  description: Ref is the branch/tag/ref to build.
                  type: string
              required:
              - accountSecret
              - desc
              - gittype
              - owner
              - private
              type: object
            gitTemplate:
              description: Git
              properties:
                accountSecret:
                  description: The token of the account that the template will copy
                    to
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                owner:
                  description: Account of the template to copy
                  type: string
                repo:
                  description: Repo to copy
                  type: string
              required:
              - accountSecret
              - owner
              - repo
              type: object
            quotaSize:
              type: string
            team:
              type: string
          required:
          - desc
          - displayName
          - env
          - team
          type: object
        status:
          description: ProjectInitializeStatus defines the observed state of ProjectInitialize
          properties:
            namespaceCreated:
              type: boolean
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
