apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-initialize
spec:
  replicas: 1
  selector:
    matchLabels:
      name: project-initialize
  template:
    metadata:
      labels:
        name: project-initialize
    spec:
      serviceAccountName: project-initialize
      containers:
        - name: project-initialize-operator
          image: "quay.io/redhat-cop/project-initialize-operator:latest"
          command:
          - project-initialize-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "project-initialize"
