kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: project-initialize
subjects:
- kind: ServiceAccount
  name: project-initialize
  namespace: "project-operator"
roleRef:
  kind: ClusterRole
  name: project-initialize
  apiGroup: rbac.authorization.k8s.io
